Remove .treatAllWarnings(as: .error) from Package.swift (#1)
Xcode automatically injects -suppress-warnings into the swiftc
invocation for all SPM dependency targets. This conflicts with
.treatAllWarnings(as: .error), producing:

    error: Conflicting options '-warnings-as-errors' and '-suppress-warnings'